_wandb:
    value:
        cli_version: 0.19.1
        code_path: code/linear_prob_simple_args.py
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "3":
                - 13
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
