# Training Configuration
seed: 42
learning_rate: 1e-4  
epochs: 100
batch: 2

# Model Configuration
model_name: mocov2
pretrained_weights: '/path/to/moco_v2_200ep_pretrain.pth.tar'
train_from_scratch: False  # If True, equivalent to model_name = "scratch"
train_backbone: False      # False = frozen backbone, True = finetune backbone

# Weights & Biases Configuration
wandb: True
project: wandb_project_name
name: wandb_trial_name

# Data Paths
image_folder: /path/to/images_dir # /path/to/segmentations_eval/active_corrals_data/images
mask_folder: /path/to/masks_dir   # /path/to/segmentations_eval/active_corrals_data/masks
output_dir: /path/to/output_dir