# this corresponds to the default config
train:
  dataset_path: ImageNet:split=TRAIN:root=/home/guoj5/Documents/datasets/imagenet1k:extra=/home/guoj5/Documents/datasets/imagenet1k_meta
  batch_size_per_gpu: 16 # i test 8 on my local pc, it is 16 for the fisrt trial 
  # this is one added, by default it is 10
  num_workers: 2

  OFFICIAL_EPOCH_LENGTH: 150 # it was 1250, i change it to 150 for the second trial 150~ 1250/8
student:
  block_chunks: 4

evaluation:
  eval_period_iterations: 1250
