# this corresponds to the default config
train:
  dataset_path: ImageNet:split=TRAIN:root=/home/guoj5/Documents/datasets/imagenet1k:extra=/home/guoj5/Documents/datasets/imagenet1k_meta
  batch_size_per_gpu: 64
student:
  block_chunks: 4
